server:
  port: 8101
spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: 172.2.0.105:8848
        namespace: cloud-demo
    gateway:
      routes:
        - id: stock-demo
          uri: lb://stock-demo
          predicates:
            - Path=/stock-service/**
            - Header=X-Request-Id,\d+ # 判断请求Headers是否具有给定名称且值与正则表达式相匹配
            - CheckAuth=shq
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Request-Color,red # 添加请求头
        - id: order-demo
          uri: lb://order-demo
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':   # 允许跨域访问的资源
            allowedOrigins: "*"   #跨域允许来源
            allowedMethods:
              - GET
              - POST



