server:
  port: 8072

spring:
  application:
    name: order-seata-demo
  cloud:
    nacos:
      discovery:
        server-addr: 172.2.0.105:8848
        namespace: cloud-demo
    alibaba:
      seata:
        tx-service-group: my_test_tx_group # seata服务事务分组

  # 数据源配置
  datasource:
    url: jdbc:mysql://172.2.0.105:3306/seata_demo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
    username: root
    password: Password123@wayzdeck.mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 设置mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.shq.demo.orderSeata.pojo
  configuration:
    mapUnderscoreToCamelCase: true


seata:
  registry:
    # 配置seata的注册中心， 告诉seata client 怎么去访问seata server(TC)
    type: nacos
    nacos:
      server-addr: 172.2.0.105:8848  # seata server 所在的nacos服务地址
      application: seata-server    # seata server 的服务名seata-server ，如果没有修改可以不配
      group: SEATA_GROUP          # seata server 所在的组，默认就是SEATA_GROUP，没有改也可以不配
  config:
    type: nacos
    nacos:
      server-addr: 172.2.0.105:8848
      group: SEATA_GROUP