server:
  port: 8041

spring:
  application:
    name: sentinel-cloud-demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
    nacos:
      discovery:
        server-addr: 172.2.0.105:8848
        namespace: cloud-demo

# 对feign的支持，sentinel整合feign进行服务降级
feign:
  sentinel:
    enabled: true
