server:
  port: 8011
spring:
  application:
    name: order-ribbon-demo
  cloud:
    nacos:
      discovery:
        server-addr: 172.2.0.105:8848
        namespace: cloud-demo

stock-demo:
  ribbon:
    # 指定使用Nacos提供的负载均衡策略（优先调用同一集群的实例，基于随机&权重）
    NFLoadBalancerRuleClassName: com.shq.demo.orderRibbon.custemRule.CustomRandomRule
ribbon:
  eager‐load:
    # 开启ribbon饥饿加载
    enabled: true
    # 配置mall‐user使用ribbon饥饿加载，多个使用逗号分隔
    clients: stock-demo